name: Pawn BIOS Dumping Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.6
        with:
          cmake-version: '3.14'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ninja
        run: pip install ninja

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          
      - name: Run tests
        run: |
          cd build
          ctest
          
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release
          
      - name: Run tests
        run: |
          cd build
          ctest
