# Revised version of build.yml

name: Pawn BIOS Dumping Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          wget -O cmake-linux.tar.gz https://cmake.org/files/v3.21/cmake-3.21.3-linux-x86_64.tar.gz
          tar -xf cmake-linux.tar.gz
          export PATH="$PWD/cmake-3.21.3-linux-x86_64/bin:$PATH"

      - name: Install Ninja
        run: |
          wget -O ninja-linux.zip https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
          unzip ninja-linux.zip
          export PATH="$PWD:$PATH"

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          wget -O cmake-windows.zip https://cmake.org/files/v3.21/cmake-3.21.3-windows-x86_64.zip
          Expand-Archive -Path cmake-windows.zip -DestinationPath .
          $env:PATH = "$PWD/cmake-3.21.3-windows-x86_64/bin;$env:PATH"

      - name: Install Ninja
        run: |
          wget -O ninja-windows.zip https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-windows.zip
          Expand-Archive -Path ninja-windows.zip -DestinationPath .
          $env:PATH = "$PWD;$env:PATH"

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - name: Run tests
        run: |
          cd build
          ctest
