# Revised version of build.yml

name: Pawn BIOS Dumping Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.14'

      - name: Set up Ninja
        uses: mesonbuild/setup-ninja@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          
      - name: Run tests
        run: |
          cd build
          ctest

  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - name: Run tests
        run: |
          cd build
          ctest
