name: pawn-bios-extractor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build

      - name: Install Dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y visualstudio2019buildtools
          choco install -y ninja

      - name: Configure CMake
        run: cmake -Bbuild -S. -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build --config $BUILD_TYPE

      - name: Package
        run: |
          mkdir -p package

          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cp build/pawn_bios_extractor package/
            tar -czf package/pawn_bios_extractor_linux.tar.gz -C package .
            echo "::set-output name=package::package/pawn_bios_extractor_linux.tar.gz"
          fi

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            copy build\pawn_bios_extractor.exe package\
            powershell -Command "Compress-Archive -Path package -DestinationPath package\pawn_bios_extractor_windows.zip"
            echo "::set-output name=package::package/pawn_bios_extractor_windows.zip"
          fi

      - name: Test
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Run unit tests
          ctest --build-config "${BUILD_TYPE}" --output-on-failure
          # Run integration tests
          # Add your integration testing commands here

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pawn-bios-extractor-artifacts
          path: package

      - name: Deploy
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Deploy to Linux servers
          # Add your deployment commands for Linux here
          ssh user@server 'mkdir -p /path/to/deploy'
          scp package/pawn_bios_extractor_linux.tar.gz user@server:/path/to/deploy

      - name: Deploy
        if: matrix.os == 'windows-latest'
        run: |
          # Deploy to Windows servers
          # Add your deployment commands for Windows here
          robocopy package \\server\path /MIR

      - name: Cleanup
        run: |
          # Perform cleanup tasks
          # Add any necessary cleanup commands here
